### ISSUE TITLE
Error on windows system:  uninitialized constant Process::RLIMIT_NOFILE

### ISSUE THREAD

**Issue by NargisTahara** [white-gecko/jekyll-rdf#197]
I am getting following error when I try to use jekyll-rdf on windows:

 

> There was an error while trying to load the gem 'jekyll-rdf'. (Bundler::GemRequireError)
> Gem Load Error is: uninitialized constant Process::RLIMIT_NOFILE

I installed jekyll using RubyInstaller by following instruction on jekyll official [website](https://jekyllrb.com/docs/windows/).
The error log is below: 
```
bundle exec jekyll serve
Traceback (most recent call last):
        10: from C:/Ruby25-x64/bin/jekyll:23:in `<main>'
         9: from C:/Ruby25-x64/bin/jekyll:23:in `load'
         8: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.5.1/exe/jekyll:9:in `<top (required)>'
         7: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.5.1/lib/jekyll/plugin_manager.rb:49:in `require_from_bundler'
         6: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler.rb:114:in `require'
         5: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:65:in `require'
         4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:65:in `each'
         3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:76:in `block in require'
         2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:76:in `each'
         1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:80:in `block (2 levels) in require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'jekyll-rdf'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant Process::RLIMIT_NOFILE
Backtrace for gem load error is:
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:205:in `<class:Persistent>'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:190:in `<top (required)>'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sparql-client-3.0.0/lib/sparql/client.rb:1:in `require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sparql-client-3.0.0/lib/sparql/client.rb:1:in `<top (required)>'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/linkeddata-2.2.4/lib/linkeddata.rb:62:in `require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/linkeddata-2.2.4/lib/linkeddata.rb:62:in `<module:LinkedData>'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/linkeddata-2.2.4/lib/linkeddata.rb:1:in `<top (required)>'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-rdf-2.3.0/lib/jekyll-rdf.rb:30:in `require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-rdf-2.3.0/lib/jekyll-rdf.rb:30:in `<top (required)>'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:81:in `require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:76:in `each'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:76:in `block in require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:65:in `each'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:65:in `require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler.rb:114:in `require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.5.1/lib/jekyll/plugin_manager.rb:49:in `require_from_bundler'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.5.1/exe/jekyll:9:in `<top (required)>'
C:/Ruby25-x64/bin/jekyll:23:in `load'
C:/Ruby25-x64/bin/jekyll:23:in `<main>'
Bundler Error Backtrace:
```

**Comment by white-gecko** [comment]
@Simaris are you able to reproduce this issue on a Windows system?

**Comment by Simaris** [comment]
I could reproduce the error on windows 7. Since our plugin worked on windows at some point in the past, my first guess is that some of our features introduced some dependencies that are not supported on windows.

**Comment by Simaris** [comment]
I could make it work by editing my `Gemfile`:

```ruby
source 'https://rubygems.org'

group :jekyll_plugins do
  gem 'net-http-persistent', '2.9'   # The gem that causes problems on windows
  gem 'jekyll-rdf', '>= 3.0.0'
end
```

Than update your sites bundler profile:
```
bundle update net-http-persistent
```

and it should be good to go
